"""empty message

Revision ID: 1b5e24ac0238
Revises: 5e3f7b11810d
Create Date: 2022-08-10 17:01:20.965375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1b5e24ac0238"
down_revision = "5e3f7b11810d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "results",
        sa.Column(
            "applicant_status",
            postgresql.ENUM("processed", "pending", "failed", name="status"),
            nullable=True,
        ),
    )
    op.drop_column("results", "status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "results",
        sa.Column(
            "status",
            postgresql.ENUM("processed", "pending", "failed", name="status"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("results", "applicant_status")
    # ### end Alembic commands ###
