"""feat model applicant

Revision ID: 45caee0a75dc
Revises: 1b5e24ac0238
Create Date: 2022-10-02 13:25:50.718915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45caee0a75dc'
down_revision = '1b5e24ac0238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('identifify_number', sa.BigInteger(), nullable=True))
    op.add_column('applicants', sa.Column('nationality', postgresql.ENUM('VIETNAM', 'SINGAPORE', 'LAOS', 'INDONESIA', 'THAILAND', 'CAMPUCHIA', 'MALAYSIA', name='countries'), nullable=True))
    op.add_column('applicants', sa.Column('new_applicant', sa.Boolean(), nullable=True))
    op.add_column('applicants', sa.Column('permanent_residence', sa.String(), nullable=True))
    op.add_column('applicants', sa.Column('phone_number', sa.BigInteger(), nullable=True))
    op.add_column('applicants', sa.Column('place', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicants', 'place')
    op.drop_column('applicants', 'phone_number')
    op.drop_column('applicants', 'permanent_residence')
    op.drop_column('applicants', 'new_applicant')
    op.drop_column('applicants', 'nationality')
    op.drop_column('applicants', 'identifify_number')
    # ### end Alembic commands ###
