"""identify number

Revision ID: 807d13ddf580
Revises: 45caee0a75dc
Create Date: 2022-10-02 13:50:26.997754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807d13ddf580'
down_revision = '45caee0a75dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('identify_number', sa.BigInteger(), nullable=True))
    op.drop_column('applicants', 'identifify_number')
    op.add_column('applicants', sa.Column("country", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('identifify_number', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('applicants', 'identify_number')
    op.drop_column('applicants', 'country')
    # ### end Alembic commands ###
